Homework2
yozhikOm/FindYourMovie pull request #2
Opened 2021-05-04 23:01 UTC by yozhikOm

2021-05-17 09:57 UTC, baidala requested changes
баг при добавлении в избранное -  добавляем несколько фильмов.  переходим в избранное. нажимаем Назад. и в общем списке  все сердечки обнуляются.
аналогично при перевороте екрана все иконки сбрасываются по-дефолту

2021-05-17 09:57 UTC, baidala commented on app/src/main/java/com/example/findyourmovie/MainActivity.kt
> +    private val items = mutableListOf(
рекомендую вынести список в синглтон   object DataRepository.
так будет удобнее с ним работать из разных активити

2021-05-17 09:57 UTC, baidala commented on app/src/main/java/com/example/findyourmovie/MainActivity.kt
> +    private var favoriteItems = mutableListOf<MovieItem>()
второй список можно не использовать т.к. есть в  MovieItem  isFavorite  - можно фильтровать по этому полю

2021-05-20 15:49 UTC, yozhikOm commented on app/src/main/java/com/example/findyourmovie/MainActivity.kt
> +    private val items = mutableListOf(
к сожалению, не разобралась, что из себя представляет синглтон object DataRepository, гугл мало помог.
работа с БД предстоит в след.домашках

2021-05-20 15:50 UTC, yozhikOm commented on app/src/main/java/com/example/findyourmovie/MainActivity.kt
> +    private var favoriteItems = mutableListOf<MovieItem>()
@baidala это какой-то рудимент, удалила

2021-05-20 15:52 UTC, yozhikOm commented on app/src/main/java/com/example/findyourmovie/MainActivity.kt
> +    private val items = mutableListOf(
@baidala остальное поправила, вопросы в TODO остаются актуальными

2021-05-22 13:11 UTC, baidala requested changes
нужно доделать чтоб детали фильма открывались

2021-05-22 13:11 UTC, baidala commented on app/src/main/java/com/example/findyourmovie/MainActivity.kt
> +    private fun changeLocale(locale: Locale) {
в простом случае - язык приложения  будет тот, что выставлен на телефоне. для дз этого достаточно. т.е. просто создать два набора ресурсов.  для того чтоб переключать язык независимо от системного можно  использовать ContextWrapper. в меню пользователь выбирает нужный язык из доступных. записываем в префс  код для простоты  - ru/en и т.д. и вызываем activity.recreate().  в Application/Activity  есть attachBaseContext().  в этом методе  изменяем и сохраняем полученный контекст ( ContextWrapper(baseContext) ) как переменную, чтоб в дальнейшем использовать.  в этом контексте изменяем локаль в конфигурации на ту что в префсах. потом во всех текстовых полях программно сетим текст в нужной локали  
`filmListTitle.setText ( getBaseContext().getString(R.string.title)  )`
getBaseContext() -  свой метод, который возвращает сохраненный контек (ContexWrapper) с нужной локалью. это важно т.к. в разных активити контекст может быть разный и локаль тоже может быть разная

2021-05-22 13:11 UTC, baidala commented on app/src/main/java/com/example/findyourmovie/MainActivity.kt
> +        resources.updateConfiguration(configuration, null)
```
if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
            configuration.setLocale(newLocale);
            LocaleList localeList = new LocaleList(newLocale);
            LocaleList.setDefault(localeList);
            configuration.setLocales(localeList);
            context = context.createConfigurationContext(configuration);
        } else {
            configuration.setLocale(newLocale);
            context = context.createConfigurationContext(configuration);
        }
        resources.updateConfiguration(configuration, displayMetrics);
```

2021-05-22 13:11 UTC, baidala commented on app/src/main/java/com/example/findyourmovie/MainActivity.kt
> +        //TODO не меняет на portrait, когда вверх ногами, потому что эмулятор?
на реальном девайс все переворачивается как надо - портрет - одна колонка. альбом - две колонки

2021-05-22 13:11 UTC, baidala commented on app/src/main/java/com/example/findyourmovie/MovieAdapter.kt
> +            //TODO как реализовать нажатие на кнопку Details ??
именно как в закоменченом коде. только ваш clickListener  должен имплементить ваш интерфейс OnFilmClickListener (можете прямо в адаптере описать как public interface ).  в котором будет  метод onDetailsClick(item)  (и другие onFavoriteClick(item) ).
и при клике на детали вы вызываете  clickListener.onDetailsClick(item)  а при клике на сердечко  clickListener.onFavoriteClick(item)

2021-05-22 13:11 UTC, baidala commented on app/src/main/java/com/example/findyourmovie/MovieAdapter.kt
> +        //TODO Как исключить подобный хэдер из грида в ландшафтной ориентации, т.е. разместить его выше грида??
http://blog.sqisland.com/2014/12/recyclerview-grid-with-header.html

2021-05-26 13:22 UTC, yozhikOm commented on app/src/main/java/com/example/findyourmovie/MainActivity.kt
> +    private fun changeLocale(locale: Locale) {
@baidala в др.раз доделаю, спасибо за объяснение!

2021-05-26 13:23 UTC, yozhikOm commented on app/src/main/java/com/example/findyourmovie/MovieAdapter.kt
> +            //TODO как реализовать нажатие на кнопку Details ??
@baidala доработала

2021-05-26 13:23 UTC, yozhikOm commented on app/src/main/java/com/example/findyourmovie/MovieAdapter.kt
> +        //TODO Как исключить подобный хэдер из грида в ландшафтной ориентации, т.е. разместить его выше грида??
@baidala  получилось, спасибо!

2021-05-28 08:34 UTC, merged