feat: homework3 with crash when return screen
yozhikOm/FindYourMovie pull request #3
Opened 2021-05-28 08:39 UTC by yozhikOm

2021-05-30 15:52 UTC, baidala requested changes
еще надо  исправить дефолтные конструкторы для фрагментов

2021-05-30 15:52 UTC, baidala commented on app/src/main/java/com/example/findyourmovie/FavoritesListFragment.kt
> +class FavoritesListFragment(val items: MutableList<MovieItem>) : Fragment() {
креши у вас изза того что нет пустого дефолтного конструктора.
т.е должно быть 
`class FavoritesListFragment : Fragment() {..
private lateinit var items: List<MovieInfo>
`
и метод для передачи аргументов в фрагмент
```
companion object {
        const val ITEMS = "ITEMS"

        @JvmStatic
        fun newInstance(items: ArrayList<MovieItem>): MovieListFragment {
            return MovieListFragment().apply {
                arguments = Bundle().apply {
                    putParcelableArrayList(ITEMS, items)
                }
            }
        }
    }
```
потом в onViewCreated()  достаете этот список.
и так во всех фрагментах.
список можно передавать в доп.классе со списком внутри   через putParcelable/putSerializable

2021-05-30 15:52 UTC, baidala commented on app/src/main/java/com/example/findyourmovie/FavoritesListFragment.kt
> +        //TODO как поменять сердечко на корзину??
иконки сеттятся в viewHoldere. рекомендую использовать схему
фрагмент +recyclerView + adapter + viewHolder   
для каждого франмента делать свои адаптер и вьюхолдер. и тогда в каждом вьюхолдере можно разные layout  использовать

2021-05-30 15:52 UTC, baidala commented on app/src/main/java/com/example/findyourmovie/MainActivity.kt
> +    //TODO корректо ли оставлять этот метод пустым и все изменения с элементом производить во фрагменте?
в данном дз - активити выступает в роли контейнера для фрагментов и  хранилища для списка фильмов.
активити  меняет только поля isFavorite.  фрагмент отвечает за отрисовку списка на екране. чтобы не было пустых методов - лучше разделить на разные интерфейсы и использовать только то чно нужно в активити

2021-05-30 15:52 UTC, baidala commented on app/src/main/java/com/example/findyourmovie/MovieAdapter.kt
> +//TODO правильно ли использовать в адаптере интерфейс фрагмента? - MovieListFragment.OnMovieClickListener
интерфейсы лучше вынести в отдельный файл/класс

2021-06-03 17:24 UTC, yozhikOm commented on app/src/main/java/com/example/findyourmovie/FavoritesListFragment.kt
> +        //TODO как поменять сердечко на корзину??
@baidala пока оставлю сердечко, чтобы не создавать путаницы с большим количеством файлов

2021-06-03 17:24 UTC, yozhikOm commented on app/src/main/java/com/example/findyourmovie/MovieAdapter.kt
> +//TODO правильно ли использовать в адаптере интерфейс фрагмента? - MovieListFragment.OnMovieClickListener
@baidala вынесла

2021-06-03 17:25 UTC, yozhikOm commented on app/src/main/java/com/example/findyourmovie/FavoritesListFragment.kt
> +class FavoritesListFragment(val items: MutableList<MovieItem>) : Fragment() {
@baidala получилось

2021-06-03 17:26 UTC, yozhikOm commented on app/src/main/java/com/example/findyourmovie/MainActivity.kt
> +    //TODO корректо ли оставлять этот метод пустым и все изменения с элементом производить во фрагменте?
@baidala разделила интерфейсы

2021-06-06 15:25 UTC, baidala requested changes
повороты екрана теперь нормально отрабатывают. надо большой постер на екране деталей доделать чтоб туда подгружалась картинка

2021-06-06 15:25 UTC, baidala commented on app/src/main/res/layout/fragment_movie_details.xml
> +                android:layout_width="match_parent"
тут надо добавить id  и подгружать сюда постер. он должен сворачиватся.  а  imageView  (id = coverImg )  не нужна. на этом экране у вас большой постер и под ним описание. постер сворачивается/разворачивается

2021-06-06 15:25 UTC, baidala commented on app/src/main/res/layout/fragment_movie_details.xml
> +                android:id="@+id/coverImg"
на этом экране только большой постер нужен

2021-06-26 15:51 UTC, merged